spring:
  application:
    name: gateway
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 7001
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
    ## 实例定时拉注册表的时间 默认30秒
    registryFetchIntervalSeconds: 3
    ## 心跳间隔，默认30秒(???貌似没起效)
    leaseRenewalIntervalInSeconds: 3

zuul:
  retryable: true
  ## 不自动创建路由，全部由后台表控制
  ignored-services: '*'
##  routes:
##    client-a:
##      path: /client/**
##      serviceId: client-a
yunhua:
  component:
    doc:
      enabled: true
